#+TITLE: Python Setup Windows
#+AUTHOR: Peter Polidoro
#+EMAIL: peterpolidoro@gmail.com

* Repository Information
  - Author :: Peter Polidoro
  - License :: BSD

* Setup Git and Git Bash

  [[https://github.com/janelia-experimental-technology/git_setup]]

* Setup Python

** Python 3

   Download Python 3.X Windows Installer from:

   [[https://www.python.org/download]]

   Install all features, including pip and adding python.exe to Path.

   Restart computer.

   Open git bash terminal:

   Make a directory to store virtual environments:

   #+BEGIN_SRC sh
     mkdir ~/venvs
   #+END_SRC

   Create and activate a virtual environment:

   [[https://packaging.python.org/tutorials/installing-packages/#creating-virtual-environments]]

   #+BEGIN_SRC sh
     python -m venv ~/venvs/example_env
     source ~/venvs/example_env/Scripts/activate
   #+END_SRC

   In an activated virtual environment, upgrade ipython:

   #+BEGIN_SRC sh
     pip install ipython --upgrade
   #+END_SRC

** Python 2
   Or download Python 2.7.X Windows Installer from:

   [[https://www.python.org/download]]

   Install all features, including pip and adding python.exe to Path.

   Restart computer.

   Open git bash terminal:

   Upgrade pip:

   Install virtualenv:

   #+BEGIN_SRC sh
     pip install virtualenv --upgrade
   #+END_SRC

   Make a directory to store virtual environments:

   #+BEGIN_SRC sh
     mkdir ~/venvs
   #+END_SRC

   Create and activate a virtual environment:

   [[https://packaging.python.org/tutorials/installing-packages/#creating-virtual-environments]]

   #+BEGIN_SRC sh
     virtualenv ~/venvs/example_env
     source ~/venvs/example_env/Scripts/activate
   #+END_SRC

   In an activated virtual environment, upgrade pip and ipython:

   #+BEGIN_SRC sh
     pip install pip --upgrade
     pip install ipython --upgrade
   #+END_SRC
